version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rahasia
      - POSTGRES_DB=belajar
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  backed:
    build: ./backend
    ports: 
      - 8080:8080
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - 8081:8080