name: Go CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.x'
      - name: Install dependencies
        working-directory: ./backend
        run: go get .
      
      - name: Build
        working-directory: ./backend
        run: go build -v ./...
        
      - name: Test with the Go CLI
        working-directory: ./backend
        run: go test
      
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: cisavalentino/todo-backend
          working-directory: frontend
          tags: v1, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
