name: Node CI
on: [push]

jobs:
  build:
    name: Node CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: 'frontend'

      - name: Run build in sub-folder
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: 'frontend' 
          
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          working-directory: frontend
          image: cisavalentino/todo-frontend
          tags: v1, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

